name: modern_authentication_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
   - family: Prime
     fonts:
       - asset: assets/fonts/Prime-Light.otf
         weight: 300
       - asset: assets/fonts/Prime-Regular.otf
         weight: 400
   - family: Inter
     fonts:
       - asset: assets/fonts/Inter_18pt-Regular.ttf
         weight: 400
       - asset: assets/fonts/Inter_18pt-Bold.ttf
         weight: 700

   - family: Roboto
     fonts:
       - asset: assets/fonts/Roboto_Condensed-Regular.ttf
         weight: 400
       - asset: assets/fonts/Roboto_Condensed-Bold.ttf
         weight: 700